#!/usr/bin/env bash

#!/usr/bin/env bash

# Update package lists
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a simple HTML file
echo "Hello World" | sudo tee /var/www/html/index.html

# Configure Nginx to redirect /redirect_me to YouTube
sudo sed -i '/server_name _;/a \ \ \ \ location /redirect_me {\n \ \ \ \ \ \ \ \ return 301 https://www.youtube.com/;\n \ \ \ \ }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

